"""init schema

Revision ID: ffe18c8cdd2f
Revises: 
Create Date: 2025-09-24 21:40:21.957314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe18c8cdd2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('direction', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'asset_id')
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'direction')
    # ### end Alembic commands ###
